name : Terraform Checks
on:
  push:

permissions: read-all

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}
    
    - name: checkout code
      uses: actions/checkout@v4

    - name: checkout other repo
      uses: actions/checkout@v4
      with: 
        repository: Manoj1247/terraform-modules-network
        token: ${{ secrets.PAT }}
        path: modules/network

    - name: checkout database repo
      uses: actions/checkout@v4
      with: 
        repository: Manoj1247/terraform-modules-database
        token: ${{ secrets.PAT }}
        path: modules/database
        ref: "0.0.2"

    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3
        terraform_wrapper: false
    
    - name: check format
      run: terraform fmt -recursive -check

    - name: initialize terraform
      run : |
        sed -i -e "s/git@github\.com:Manoj1247\/terraform\-modules\-/\.\/modules\//g" main.tf
        sed -i -e "s/\.git.*/\"/g" main.tf
        rm backend.tf
        cat main.tf
        terraform init
        terraform validate 

  

