name : Terraform Checks
on:
  push:

permissions: read-all

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
  
    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3
        terraform_wrapper: false
    
    - name: check format
      run: terraform fmt -recursive -check

    - name: initialize terraform
      run : |
        export TF_TOKEN_github_com=${{ secrets.PAT }}
        sed -i -e "s/git@github.com:/https:\/\/git@github.com\//g" main.tf
        cat main.tf
        terraform init
        terraform plan
        terraform validate 

  

