name : Terraform Checks
on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with: 
        ssh-key: 
  
    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3
    
    - name: check format
      run: terraform fmt -recursive

    - name: initialize terraform
      run : terraform init && terraform plan && terraform validate 
      with :
        ssh-key: ${{secrets.SSH_PRIVATE_KEY}}

  

