name : Terraform Checks
on:
  push:

permissions: read-all

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
    - name: checkout code
      uses: actions/checkout@v4
  
    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3
        terraform_wrapper: false
    
    - name: check format
      run: terraform fmt -recursive -check

    - name: initialize terraform
      run : |
        echo credentials "github.com" = { >> ~/.terraformrc
        echo    token = "${{ secrets.PAT }}" >> ~/.terraformrc
        echo } >> ~/.terraformrc
        cat ~/.terraformrc
        sed -i -e "s/github.com/https:\/\/git:${{ secrets.PAT }}@github.com/g" main.tf
        cat main.tf
        terraform init
        terraform plan
        terraform validate 

  

